on:
  pull_request:

name: Test Transition Issue

jobs:
  test-transition-issue:
    name: Transition Issue
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Find Issue Key
      id: create
      uses: atlassian/gajira-find-issue-key@v3
      with:
        from: branch

    - name: Transition issue
      uses: atlassian/gajira-transition@master
      with:
        issue: ${{ steps.create.outputs.issue }}
        transition: "In Progress"

    - name: Comment PR
      uses: sbimochan/jira-link-commenter@v2.4
      with:
        jira-project-url: https://testgithun.atlassian.net/
        #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        custom-comment: "Thank you for your contribution! :confetti_ball:"